apiVersion: v1
kind: Service
metadata:
  name: technical-test
spec:
  type: ClusterIP
  selector:
    app: technical-test
  ports:
    - name: http
      port: 80
      targetPort: 8290
    - name: https
      port: 443
      targetPort: 8253
